enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "both"
# excluded-patches = "'Disable zoom haptics' 'GmsCore support' 'Enable debugging' 'Announcements' 'Custom player overlay opacity' 'Theme' 'Hide player buttons' 'Enable tablet layout' 'Spoof app version' 'Wide searchbar' 'Hide filter bar' 'Hide seekbar' 'Hide crowdfunding box' 'Hide timestamp' 'Disable fullscreen ambient mode' 'Hide album cards' 'Comments' 'Hide floating microphone button' 'Alternative thumbnails' 'Restore old video quality menu' 'Playback speed' 'Disable precise seeking gesture' 'Seekbar tapping' 'Swipe controls'"
# excluded-patches = "'Swipe controls' 'Hide floating microphone button' 'Disable rolling number animations' 'Hide crowdfunding box' 'Custom player overlay opacity' 'Theme' 'Enable tablet layout' 'Restore old seekbar thumbnails' 'Wide searchbar' 'Enable debugging' 'GmsCore support' 'Disable zoom haptics' 'Announcements'"
excluded-patches = "'Remove viewer discretion dialog' 'Swipe controls' 'Spoof app version' 'Theme' 'Alternative thumbnails' 'Bypass image region restrictions' 'Announcements' 'Always repeat' 'GmsCore support'"
included-patches = ""
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
module-prop-name = "youtube-revanced-ixovo"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"


[Music]
build-mode = "both"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
included-patches = "'Permanent shuffle' 'Permanent repeat'"
excluded-patches = "'GmsCore support'"
module-prop-name = "youtubemusic-revanced-ixovo"
